[package]
name = "pi_pico_blink"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m-rt = "0.7.3"
panic-halt = "0.2.0"
rp-pico = "0.9.0"
embedded-hal = "0.2.7"
heapless = "0.8.0"
hd44780-driver = "0.4.0"
dht-sensor = "0.2.1"
